### ISSUE TITLE
[Task] Server needs to understand player positions within the world

### ISSUE THREAD

**Issue by Qinusty** [veloren/game#10]
All players positions shall be tracked by the Server crate.

**Comment by Qinusty** [comment]
Player positions should use nalgebra for easy integration with voxygen

**Comment by zesterer** [comment]
We don't need movement prediction or anything like that at this stage. We can go for a pretty dumb naive approach: just relay coordinates to all other clients

**Comment by Qinusty** [comment]
Player positions now use nalgebra::Vector3. Forgot to tag the [commit ](https://github.com/veloren/game/commit/184766a89a9aaab603d41ca432ef473ba45c660d) with issue #10
