### ISSUE TITLE
[Task] Fix major slowdown in server crate

### ISSUE THREAD

**Issue by Qinusty** [veloren/game#11]
Make worldsim internally concurrent and externally concurrent (i.e: other things can still call functions on it while a world simulation update is occuring)

**Comment by xMAC94x** [comment]
yeah you can do, however i am currently working on making the server crate using Mutex and RwLocks like Client does. does this conflict ?

**Comment by zesterer** [comment]
I don't think so. This'll be purely an issue for the `world` and `region` crates. Although I will end up changing the `world` crate's API, so you might have to do a little refactoring to handle that.
