### ISSUE TITLE
Make the choice of chunk size not hard-coded

### ISSUE THREAD

**Issue by zesterer** [veloren/game#51]
Currently, we use 16 as the chunk size. This is hard-coded in several places (you can search through the changes on https://github.com/veloren/game/commit/70408ca9bb1eb8a84ad2153f598652271ea31011 to find them all). It should be controlled by a single static constant instead.

**Comment by treenix** [comment]
I will take this.

**Comment by zesterer** [comment]
@treenix Thanks! Also worth noting that the last few commits added instances of this number hard-coded as well. It's probably best to place the static constant in `client/src/lib.rs` for now since chunks are currently only client-side.
