### ISSUE TITLE
.vox file validation test

### ISSUE THREAD

**Issue by xMAC94x** [veloren/game#62]
we need a test that simply loads all voxel files in the voxygen/vox files and tries to load them into a model.
This way Voxel Artists can know if there is any incompatibility between their uploads and the engine.

The method already exists, you just need to reuse the functions from voxygen/src/game.rs for all those files. and maybe write a test in .gitlab-ci.yaml to automatic run this

**Comment by treenix** [comment]
@xMAC94x I can't, since I'm not a collaborator of this repo
