### ISSUE TITLE
error: linking with `link.exe` failed: exit code: 1

### ISSUE THREAD

**Issue by Tigralt** [veloren/game#70]
I was trying to test the project on my machine (Windows 10) but I have some issues when running a "cargo run" on server-cli (I have the same problem with voxygen tho):

![image](https://user-images.githubusercontent.com/2451712/42337293-9bf1d48e-8086-11e8-808f-26a0ce25e387.png)

I have no idea what's exactly is happening, all I know is that I installed Rust from the README.md link, same for the SFML library (with https://github.com/jeremyletang/rust-sfml/wiki/How-to-use-rust-sfml-on-Windows). All deps are correctly downloading, but compiling doesn't work.

**Comment by zesterer** [comment]
@Tigralt Any chance you could run it with `--color never` to make it a bit easier to read? There's a lot of noise due to the incorrectly-interpreted colour codes.

**Comment by Tigralt** [comment]
My bad, here it is:
![image](https://user-images.githubusercontent.com/2451712/42337809-1df8c9f0-8088-11e8-85f6-969ffac93047.png)

**Comment by zesterer** [comment]
@Tigralt Seems like https://github.com/rust-lang/rust/issues/42744

**Comment by Tigralt** [comment]
Nice one it's working now ! I uninstalled/reinstalled Visual Studio Community, seems like something went wrong the first time.
